{
 "title": "Solar",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "watts",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "solar_now_p != 0" },
    {}
   ]
  },
  {
   "title": "Total today",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "max_over_time(solar_total_e[1d]) - max_over_time(solar_total_e[1d] offset 24h)",
     "legendFormat": "kwh/day"
    }
   ]
  },
  {
   "title": "Now",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "solar_now_p" }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(solar_total_e[1h])"
    }
   ]
  }
 ]
}